### ISSUE TITLE
Multiple countries + updates

### ISSUE THREAD

**Issue by MennoSaey** [wiktorn/Overpass-API#113]
I would like to only use for example 2 countries to keep the size to a minimum, is it possible to provide a download link to multiple countries and diffs or use multiple already locally downloaded files? how would updating them work? 

P.s. I have gone through other similar issues but these answers weren't clear to me. 

i currently have this docker compose file:

```
version: "3.8"

services:
  db:
    image: wiktorn/overpass-api
    container_name: `overpass_test`
    ports:
      - "4200:80"
    volumes:
      # mounts local subfolder into container
      - ./overpass_db:/db
    environment:
      OVERPASS_META: "no"
      OVERPASS_MODE: "init"
      OVERPASS_PLANET_URL: "file:///db/multiple_countries.osm.bz2"
      OVERPASS_DIFF_URL: "http://download.geofabrik.de/europe/germany/bayern-updates/"
      OVERPASS_RULES_LOAD: 10
      OVERPASS_UPDATE_SLEEP: 3600
```

what should be the `OVERPASS_DIFF_URL` to update a custom planet file?

an update on issue #67 is basically my question or atleast part of it. in short. what are the steps that differ from a normal installation to get a local overpass api running for lets say the benelux where there isn't a link i can provide from somwhere to download the files from or a way to select only a part of the europe planet file with osmium and only update that part too.
