### ISSUE TITLE
How to map another port using docker-compose?

### ISSUE THREAD

**Issue by e183b796621afbf902067460** [wiktorn/Overpass-API#127]
I got this one `docker-compose.yaml`:
```yaml
version: '3.8'

services:
  overpass:
    image: wiktorn/overpass-api:0.7.61.8
    container_name: overpass-app
    command:
      - "/app/docker-entrypoint.sh"
    ports:
      - 8989:8989
    environment:
      - OVERPASS_META=no
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=https://download.geofabrik.de/russia/kaliningrad-latest.osm.bz2
      - OVERPASS_UPDATE_SLEEP=86400
      - OVERPASS_RULES_LOAD=50
      - OVERPASS_STOP_AFTER_INIT=false
      - OVERPASS_ALLOW_DUPLICATE_QUERIES=yes
      - OVERPASS_USE_AREAS=false
      - OVERPASS_FASTCGI_PROCESSES=8
      - OVERPASS_SPACE=12884901888
    networks:
      - overpass-tier

networks:
  overpass-tier:
```
and I want to mount another port, but then I got problem that there is no external access to the overpass-api and I only can mount on `:80` port, maybe somebody knows how to access more flexibility?
